/**
 * **Feature: ui-upgrade, Property 1: Survey Status Badge Variant Consistency**
 * **Validates: Requirements 5.3**
 * 
 * *For any* survey with a given status (active, pending, ended), the rendered Badge component 
 * SHALL have the corresponding variant class (success for active, secondary for pending, 
 * destructive for ended).
 */
import { describe, it, expect } from 'vitest'
import * as fc from 'fast-check'
import { badgeVariants } from '@/components/ui/badge'

// Survey status types
type SurveyStatus = 'active' | 'pending' | 'ended'

// Mapping from survey status to badge variant
const statusToBadgeVariant: Record<SurveyStatus, 'success' | 'secondary' | 'destructive'> = {
  active: 'success',
  pending: 'secondary',
  ended: 'destructive',
}

// Expected CSS class patterns for each variant
const variantClassPatterns: Record<string, string> = {
  success: 'bg-success',
  secondary: 'bg-secondary',
  destructive: 'bg-destructive',
}

describe('Property 1: Survey Status Badge Variant Consistency', () => {
  it('should map any survey status to the correct badge variant class', () => {
    // Arbitrary for survey status
    const surveyStatusArb = fc.constantFrom<SurveyStatus>('active', 'pending', 'ended')

    fc.assert(
      fc.property(surveyStatusArb, (status: SurveyStatus) => {
        // Get the expected badge variant for this status
        const expectedVariant = statusToBadgeVariant[status]
        
        // Get the CSS classes generated by badgeVariants for this variant
        const generatedClasses = badgeVariants({ variant: expectedVariant })
        
        // Get the expected class pattern for this variant
        const expectedClassPattern = variantClassPatterns[expectedVariant]
        
        // Verify the generated classes contain the expected pattern
        expect(generatedClasses).toContain(expectedClassPattern)
      }),
      { numRuns: 100 }
    )
  })

  it('should ensure all status values have a defined variant mapping', () => {
    const allStatuses: SurveyStatus[] = ['active', 'pending', 'ended']
    
    fc.assert(
      fc.property(fc.constantFrom(...allStatuses), (status: SurveyStatus) => {
        // Every status should have a defined mapping
        const variant = statusToBadgeVariant[status]
        expect(variant).toBeDefined()
        
        // The variant should be one of the valid badge variants
        expect(['success', 'secondary', 'destructive']).toContain(variant)
      }),
      { numRuns: 100 }
    )
  })

  it('should produce consistent variant classes for the same status', () => {
    const surveyStatusArb = fc.constantFrom<SurveyStatus>('active', 'pending', 'ended')

    fc.assert(
      fc.property(surveyStatusArb, (status: SurveyStatus) => {
        const variant = statusToBadgeVariant[status]
        
        // Generate classes multiple times - should be consistent
        const classes1 = badgeVariants({ variant })
        const classes2 = badgeVariants({ variant })
        
        expect(classes1).toBe(classes2)
      }),
      { numRuns: 100 }
    )
  })
})
