/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SurveyRevealInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createSurvey"
      | "decryptionCallback"
      | "getEncryptedResponse"
      | "getEncryptedSum"
      | "getRespondents"
      | "getRevealedResponse"
      | "getSurvey"
      | "getSurveyCount"
      | "hasResponded"
      | "isDecryptionPending"
      | "isResponseRevealed"
      | "protocolId"
      | "requestDecryption"
      | "submitResponse"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DecryptionRequested"
      | "ResponseRevealed"
      | "ResponseSubmitted"
      | "SurveyCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createSurvey",
    values: [string, string[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionCallback",
    values: [BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedResponse",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedSum",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRespondents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRevealedResponse",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSurvey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSurveyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasResponded",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDecryptionPending",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isResponseRevealed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestDecryption",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResponse",
    values: [BigNumberish, BytesLike[], BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSurvey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRespondents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRevealedResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSurvey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSurveyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasResponded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDecryptionPending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isResponseRevealed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResponse",
    data: BytesLike
  ): Result;
}

export namespace DecryptionRequestedEvent {
  export type InputTuple = [
    surveyId: BigNumberish,
    respondent: AddressLike,
    requestId: BigNumberish
  ];
  export type OutputTuple = [
    surveyId: bigint,
    respondent: string,
    requestId: bigint
  ];
  export interface OutputObject {
    surveyId: bigint;
    respondent: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResponseRevealedEvent {
  export type InputTuple = [
    surveyId: BigNumberish,
    respondent: AddressLike,
    answers: BigNumberish[]
  ];
  export type OutputTuple = [
    surveyId: bigint,
    respondent: string,
    answers: bigint[]
  ];
  export interface OutputObject {
    surveyId: bigint;
    respondent: string;
    answers: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResponseSubmittedEvent {
  export type InputTuple = [
    surveyId: BigNumberish,
    respondent: AddressLike,
    answerCount: BigNumberish
  ];
  export type OutputTuple = [
    surveyId: bigint,
    respondent: string,
    answerCount: bigint
  ];
  export interface OutputObject {
    surveyId: bigint;
    respondent: string;
    answerCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurveyCreatedEvent {
  export type InputTuple = [
    surveyId: BigNumberish,
    title: string,
    creator: AddressLike,
    questionCount: BigNumberish
  ];
  export type OutputTuple = [
    surveyId: bigint,
    title: string,
    creator: string,
    questionCount: bigint
  ];
  export interface OutputObject {
    surveyId: bigint;
    title: string;
    creator: string;
    questionCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SurveyReveal extends BaseContract {
  connect(runner?: ContractRunner | null): SurveyReveal;
  waitForDeployment(): Promise<this>;

  interface: SurveyRevealInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createSurvey: TypedContractMethod<
    [
      title: string,
      questions: string[],
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  decryptionCallback: TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, signatures: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  getEncryptedResponse: TypedContractMethod<
    [surveyId: BigNumberish, respondent: AddressLike],
    [string[]],
    "view"
  >;

  getEncryptedSum: TypedContractMethod<
    [surveyId: BigNumberish, questionIndex: BigNumberish],
    [string],
    "view"
  >;

  getRespondents: TypedContractMethod<
    [surveyId: BigNumberish],
    [string[]],
    "view"
  >;

  getRevealedResponse: TypedContractMethod<
    [surveyId: BigNumberish, respondent: AddressLike],
    [[bigint[], string] & { answers: bigint[]; responder: string }],
    "view"
  >;

  getSurvey: TypedContractMethod<
    [surveyId: BigNumberish],
    [
      [string, string[], string, bigint, bigint, bigint, bigint] & {
        title: string;
        questions: string[];
        creator: string;
        startTime: bigint;
        endTime: bigint;
        responseCount: bigint;
        questionCount: bigint;
      }
    ],
    "view"
  >;

  getSurveyCount: TypedContractMethod<[], [bigint], "view">;

  hasResponded: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isDecryptionPending: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isResponseRevealed: TypedContractMethod<
    [surveyId: BigNumberish, respondent: AddressLike],
    [boolean],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  requestDecryption: TypedContractMethod<
    [surveyId: BigNumberish, respondent: AddressLike],
    [void],
    "nonpayable"
  >;

  submitResponse: TypedContractMethod<
    [surveyId: BigNumberish, encAnswers: BytesLike[], proofs: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createSurvey"
  ): TypedContractMethod<
    [
      title: string,
      questions: string[],
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decryptionCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, signatures: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedResponse"
  ): TypedContractMethod<
    [surveyId: BigNumberish, respondent: AddressLike],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedSum"
  ): TypedContractMethod<
    [surveyId: BigNumberish, questionIndex: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRespondents"
  ): TypedContractMethod<[surveyId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRevealedResponse"
  ): TypedContractMethod<
    [surveyId: BigNumberish, respondent: AddressLike],
    [[bigint[], string] & { answers: bigint[]; responder: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSurvey"
  ): TypedContractMethod<
    [surveyId: BigNumberish],
    [
      [string, string[], string, bigint, bigint, bigint, bigint] & {
        title: string;
        questions: string[];
        creator: string;
        startTime: bigint;
        endTime: bigint;
        responseCount: bigint;
        questionCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSurveyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasResponded"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isDecryptionPending"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isResponseRevealed"
  ): TypedContractMethod<
    [surveyId: BigNumberish, respondent: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestDecryption"
  ): TypedContractMethod<
    [surveyId: BigNumberish, respondent: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitResponse"
  ): TypedContractMethod<
    [surveyId: BigNumberish, encAnswers: BytesLike[], proofs: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DecryptionRequested"
  ): TypedContractEvent<
    DecryptionRequestedEvent.InputTuple,
    DecryptionRequestedEvent.OutputTuple,
    DecryptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ResponseRevealed"
  ): TypedContractEvent<
    ResponseRevealedEvent.InputTuple,
    ResponseRevealedEvent.OutputTuple,
    ResponseRevealedEvent.OutputObject
  >;
  getEvent(
    key: "ResponseSubmitted"
  ): TypedContractEvent<
    ResponseSubmittedEvent.InputTuple,
    ResponseSubmittedEvent.OutputTuple,
    ResponseSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "SurveyCreated"
  ): TypedContractEvent<
    SurveyCreatedEvent.InputTuple,
    SurveyCreatedEvent.OutputTuple,
    SurveyCreatedEvent.OutputObject
  >;

  filters: {
    "DecryptionRequested(uint256,address,uint256)": TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;
    DecryptionRequested: TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;

    "ResponseRevealed(uint256,address,uint8[])": TypedContractEvent<
      ResponseRevealedEvent.InputTuple,
      ResponseRevealedEvent.OutputTuple,
      ResponseRevealedEvent.OutputObject
    >;
    ResponseRevealed: TypedContractEvent<
      ResponseRevealedEvent.InputTuple,
      ResponseRevealedEvent.OutputTuple,
      ResponseRevealedEvent.OutputObject
    >;

    "ResponseSubmitted(uint256,address,uint8)": TypedContractEvent<
      ResponseSubmittedEvent.InputTuple,
      ResponseSubmittedEvent.OutputTuple,
      ResponseSubmittedEvent.OutputObject
    >;
    ResponseSubmitted: TypedContractEvent<
      ResponseSubmittedEvent.InputTuple,
      ResponseSubmittedEvent.OutputTuple,
      ResponseSubmittedEvent.OutputObject
    >;

    "SurveyCreated(uint256,string,address,uint8)": TypedContractEvent<
      SurveyCreatedEvent.InputTuple,
      SurveyCreatedEvent.OutputTuple,
      SurveyCreatedEvent.OutputObject
    >;
    SurveyCreated: TypedContractEvent<
      SurveyCreatedEvent.InputTuple,
      SurveyCreatedEvent.OutputTuple,
      SurveyCreatedEvent.OutputObject
    >;
  };
}
